java.sql.SQLSyntaxErrorException: ORA-00927: missing equal sign 수정
	<entry key="updateMemInfo">
		UPDATE
		   		TB_MEMBER
		   SET

				MEM_NAME = ?
			   ,MEM_NICKNAME = ?
			   ,MEM_EMAIL = ?
			   ,MODIFY_DATE = SYSDATE
			   ,MEM_GRADE = (SELECT MEM_GRADE_NO
                    FROM TB_MEMBER_GRADE
                    WHERE MEM_GRADE_NAME = ?)
	    WHERE
	    		MEM_NO = ?;
	</entry>